# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/aneopsy/clion-2016.3.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/aneopsy/clion-2016.3.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aneopsy/Evolve

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aneopsy/Evolve

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/aneopsy/clion-2016.3.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/aneopsy/clion-2016.3.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aneopsy/Evolve/CMakeFiles /home/aneopsy/Evolve/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aneopsy/Evolve/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named evolve

# Build rule for target.
evolve: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 evolve
.PHONY : evolve

# fast build rule for target.
evolve/fast:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/build
.PHONY : evolve/fast

src/Brain/DRAWS.o: src/Brain/DRAWS.cpp.o

.PHONY : src/Brain/DRAWS.o

# target to build an object file
src/Brain/DRAWS.cpp.o:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Brain/DRAWS.cpp.o
.PHONY : src/Brain/DRAWS.cpp.o

src/Brain/DRAWS.i: src/Brain/DRAWS.cpp.i

.PHONY : src/Brain/DRAWS.i

# target to preprocess a source file
src/Brain/DRAWS.cpp.i:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Brain/DRAWS.cpp.i
.PHONY : src/Brain/DRAWS.cpp.i

src/Brain/DRAWS.s: src/Brain/DRAWS.cpp.s

.PHONY : src/Brain/DRAWS.s

# target to generate assembly for a file
src/Brain/DRAWS.cpp.s:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Brain/DRAWS.cpp.s
.PHONY : src/Brain/DRAWS.cpp.s

src/Brain/DWRAON.o: src/Brain/DWRAON.cpp.o

.PHONY : src/Brain/DWRAON.o

# target to build an object file
src/Brain/DWRAON.cpp.o:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Brain/DWRAON.cpp.o
.PHONY : src/Brain/DWRAON.cpp.o

src/Brain/DWRAON.i: src/Brain/DWRAON.cpp.i

.PHONY : src/Brain/DWRAON.i

# target to preprocess a source file
src/Brain/DWRAON.cpp.i:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Brain/DWRAON.cpp.i
.PHONY : src/Brain/DWRAON.cpp.i

src/Brain/DWRAON.s: src/Brain/DWRAON.cpp.s

.PHONY : src/Brain/DWRAON.s

# target to generate assembly for a file
src/Brain/DWRAON.cpp.s:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Brain/DWRAON.cpp.s
.PHONY : src/Brain/DWRAON.cpp.s

src/Forms.o: src/Forms.cpp.o

.PHONY : src/Forms.o

# target to build an object file
src/Forms.cpp.o:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Forms.cpp.o
.PHONY : src/Forms.cpp.o

src/Forms.i: src/Forms.cpp.i

.PHONY : src/Forms.i

# target to preprocess a source file
src/Forms.cpp.i:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Forms.cpp.i
.PHONY : src/Forms.cpp.i

src/Forms.s: src/Forms.cpp.s

.PHONY : src/Forms.s

# target to generate assembly for a file
src/Forms.cpp.s:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Forms.cpp.s
.PHONY : src/Forms.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Unit.o: src/Unit.cpp.o

.PHONY : src/Unit.o

# target to build an object file
src/Unit.cpp.o:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Unit.cpp.o
.PHONY : src/Unit.cpp.o

src/Unit.i: src/Unit.cpp.i

.PHONY : src/Unit.i

# target to preprocess a source file
src/Unit.cpp.i:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Unit.cpp.i
.PHONY : src/Unit.cpp.i

src/Unit.s: src/Unit.cpp.s

.PHONY : src/Unit.s

# target to generate assembly for a file
src/Unit.cpp.s:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/Unit.cpp.s
.PHONY : src/Unit.cpp.s

src/World.o: src/World.cpp.o

.PHONY : src/World.o

# target to build an object file
src/World.cpp.o:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/World.cpp.o
.PHONY : src/World.cpp.o

src/World.i: src/World.cpp.i

.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s

.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

src/glview.o: src/glview.cpp.o

.PHONY : src/glview.o

# target to build an object file
src/glview.cpp.o:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/glview.cpp.o
.PHONY : src/glview.cpp.o

src/glview.i: src/glview.cpp.i

.PHONY : src/glview.i

# target to preprocess a source file
src/glview.cpp.i:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/glview.cpp.i
.PHONY : src/glview.cpp.i

src/glview.s: src/glview.cpp.s

.PHONY : src/glview.s

# target to generate assembly for a file
src/glview.cpp.s:
	$(MAKE) -f CMakeFiles/evolve.dir/build.make CMakeFiles/evolve.dir/src/glview.cpp.s
.PHONY : src/glview.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... evolve"
	@echo "... src/Brain/DRAWS.o"
	@echo "... src/Brain/DRAWS.i"
	@echo "... src/Brain/DRAWS.s"
	@echo "... src/Brain/DWRAON.o"
	@echo "... src/Brain/DWRAON.i"
	@echo "... src/Brain/DWRAON.s"
	@echo "... src/Forms.o"
	@echo "... src/Forms.i"
	@echo "... src/Forms.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Unit.o"
	@echo "... src/Unit.i"
	@echo "... src/Unit.s"
	@echo "... src/World.o"
	@echo "... src/World.i"
	@echo "... src/World.s"
	@echo "... src/glview.o"
	@echo "... src/glview.i"
	@echo "... src/glview.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

